// Canonical common.cpp command ownership after the temporary Gate 3 prefix.
// Keep these implementations in sync with the native common.cpp tail until
// that file can compile without KISAK_GATE3_COM_INIT_PREFIX.

#include <qcommon/cmd.h>
#include <qcommon/qcommon.h>
#include <universal/com_files.h>
#include <universal/q_shared.h>

#include <cstdint>

void __cdecl Key_WriteBindings(std::int32_t localClientNum, std::int32_t file);
void __cdecl Con_WriteFilterConfigString(std::int32_t file);

namespace
{
cmd_function_s s_quitCommand;
cmd_function_s s_writeConfigCommand;
cmd_function_s s_writeDefaultsCommand;
} // namespace

void __cdecl Com_WriteDefaultsToFile(char *filename)
{
    const int file = FS_FOpenFileWrite(filename);
    if (file)
    {
        FS_Printf(file, "// generated by Call of Duty, do not modify\n");
        Dvar_WriteDefaults(file);
        FS_FCloseFile(file);
    }
    else
    {
        Com_Printf(16, "Couldn't write %s.\n", filename);
    }
}

void __cdecl Com_WriteConfig_f()
{
    char filename[68];

    if (Cmd_Argc() == 2)
    {
        I_strncpyz(filename, Cmd_Argv(1), 64);
        Com_DefaultExtension(filename, 0x40u, ".cfg");
        Com_Printf(0, "Writing %s.\n", filename);
        Com_WriteConfigToFile(0, filename);
    }
    else
    {
        Com_Printf(0, "Usage: writeconfig <filename>\n");
    }
}

void __cdecl Com_WriteConfigToFile(int localClientNum, char *filename)
{
    const int file = FS_FOpenFileWriteToDir(filename, "players");
    if (file)
    {
        FS_Printf(file, "// generated by Call of Duty, do not modify\n");
        FS_Printf(file, "unbindall\n");
        Key_WriteBindings(localClientNum, file);
        Dvar_WriteVariables(file);
        Con_WriteFilterConfigString(file);
        FS_FCloseFile(file);
    }
    else
    {
        Com_Printf(16, "Couldn't write %s.\n", filename);
    }
}

void __cdecl Com_WriteDefaults_f()
{
    char filename[68];

    if (Cmd_Argc() == 2)
    {
        I_strncpyz(filename, Cmd_Argv(1), 64);
        Com_DefaultExtension(filename, 0x40u, ".cfg");
        Com_Printf(0, "Writing %s.\n", filename);
        Com_WriteDefaultsToFile(filename);
    }
    else
    {
        Com_Printf(0, "Usage: writedefaults <filename>\n");
    }
}

void Com_RegisterRuntimeCommands()
{
    Cmd_AddCommandInternal("quit", Com_Quit_f, &s_quitCommand);
    Cmd_AddCommandInternal(
        "writeconfig", Com_WriteConfig_f, &s_writeConfigCommand);
    Cmd_AddCommandInternal(
        "writedefaults", Com_WriteDefaults_f, &s_writeDefaultsCommand);
}
