#pragma once
#include <cstdint>

#define DPVS_PORTAL_MAX_PLANES 16

struct GfxCell;
struct GfxPortal;

struct GfxMatrix // sizeof=0x40
{                                       // ...
    float m[4][4];                      // ...
};

struct GfxViewParms // sizeof=0x140
{                                       // ...
    GfxMatrix viewMatrix;
    GfxMatrix projectionMatrix;         // ...
    GfxMatrix viewProjectionMatrix;     // ...
    GfxMatrix inverseViewProjectionMatrix; // ...
    float origin[4];                    // ...
    float axis[3][3];                   // ...
    float depthHackNearClip;
    float zNear;
    int pad;
};

struct DpvsPlane // sizeof=0x14
{                                       // ...
    float coeffs[4];                    // ...
    uint8_t side[3];            // ...
    uint8_t pad;
};

enum DpvsClipChildren : int
{                                       // ...
    DPVS_DONT_CLIP_CHILDREN = 0x0,
    DPVS_CLIP_CHILDREN = 0x1,
};

enum DpvsForceBevels : int
{                                       // ...
    DPVS_DONT_FORCE_BEVELS = 0x0,
    DPVS_FORCE_BEVELS = 0x1,
};

struct DpvsPlanes // sizeof=0x8
{                                       // ...
    const DpvsPlane *planes;            // ...
    int count;                          // ...
};
struct DpvsClipPlaneSet // sizeof=0x44
{                                       // ...
    const DpvsPlane *planes[16];        // ...
    uint32_t count;                 // ...
};

struct DpvsStaticCellCmd // sizeof=0xC
{                                       // ...
    const DpvsPlane *planes;            // ...
    const GfxCell *cell;                // ...
    uint8_t planeCount;         // ...
    uint8_t frustumPlaneCount;  // ...
    uint16_t viewIndex;         // ...
};

union GfxHullPointsPool // sizeof=0x200
{
    GfxHullPointsPool *nextFree;
    float points[64][2];
};

struct PortalHeapNode // sizeof=0x8
{                                       // ...
    GfxPortal *portal;
    float dist;
};

struct DpvsView // sizeof=0x120
{                                       // ...
    uint32_t renderFxFlagsCull;
    DpvsPlane frustumPlanes[14];        // ...
    int frustumPlaneCount;              // ...
};

struct DpvsGlobals // sizeof=0xAE78
{                                       // ...
    DpvsPlane viewPlane;                // ...
    DpvsPlane fogPlane;                 // ...
    DpvsPlane *nearPlane;               // ...
    DpvsPlane *farPlane;                // ...
    const GfxMatrix *viewProjMtx;       // ...
    const GfxMatrix *invViewProjMtx;    // ...
    float viewOrg[4];                   // ...
    int viewOrgIsDir;                   // ...
    int queuedCount;                    // ...
    PortalHeapNode *portalQueue;        // ...
    GfxHullPointsPool *nextFreeHullPoints; // ...
    float cullDist;                     // ...
    DpvsPlane childPlanes[2048];        // ...
    DpvsView views[4][3];               // ... //[localclientNum][SCENE_VIEW_CAMERA]
    uint32_t cameraCellIndex;       // ...
    DpvsPlane *sideFrustumPlanes;       // ...
    uint32_t *entVisBits[4];        // ...
    uint32_t *cellBits;             // ...
    uint32_t cellVisibleBits[32];   // ...
};
